### ISSUE TITLE
Adding another selector to a declaration causes improper indenting

### ISSUE THREAD

**Issue by mike-engel** [atom/language-less#1]
This is a little convoluted and a rare case, but it happens. Here's an example.

Original:

``` less
.some-class {
    .some-nested-class {
        background: white;
    }
}
```

Now, let's say I want to add another selector along with the nested selector. When adding a new line, it indents at the beginning of the line, but keeps the opening brace in the proper place:

``` less
.some-class {
    .some-nested-class,
< cursor is here       {
        background: white;
    }
}
```

Now, here's the expected behavior:

``` less
.some-class {
    .some-nested-class,
    < cursor is here {
        background: white;
    }
}
```

Let me know if that doesn't make sense.
