### ISSUE TITLE
Support for BEM syntax

### ISSUE THREAD

**Issue by brunowego** [atom/language-less#36]
A lot for programmers have adhered the BEM coding style. I think be nicer support this.

```less
.c-aside {
    background-color: @color-gray;
    color: @aside-text-color;

    &__widget {
        border-bottom: 1px solid @aside-border-color;
        padding: 20px;
    }

    &__title {
        color: @color-gray-dark;
        font-size: 12px;
        font-weight: 500;
        margin-bottom: 20px;
        text-transform: uppercase;
    }
}
```

Thanks!
