### ISSUE TITLE
Cursor property looks different than other properties

### ISSUE THREAD

**Issue by aeschli** [atom/language-less#79]
_From @sheetalkamat on September 14, 2017 16:27_

The cursor property get different highlighting than other properties:

![Image](http://i.imgur.com/Z2nE8VC.png)

 
 ```css
 div {
  cursor: pointer;
  color: tomato;
}
```
