### ISSUE TITLE
@charset, @keyframes, @page, @support, @namespace scoped as variable

### ISSUE THREAD

**Issue by aeschli** [atom/language-less#80]
From https://github.com/Microsoft/vscode/issues/35300

Try the following code sample: Note that 
`@charset`, `@keyframes`, `@page`, `@support`, `@namespace`
are scoped as variables.
-> Should be a keyword, e.g. `keyword.control.at-rule.less`

```less
@charset "UTF-8";
@keyframes fadeIn {
}
@page :first {
    margin: 1in;
}
@supports (display:flex) {
}
@namespace url(jttp://www.w3.org/1999/xhtml);
@import 'ddd'
```
