### ISSUE TITLE
Mixin regression

### ISSUE THREAD

**Issue by 50Wliu** [atom/language-less#83]
```less
.markdown-preview[data-use-github-style] {
  .markdown-body(); // comment this out to fix everything

  padding: 30px; // padding is property-value
  font-size: 16px; // entity.name.tag.custom
  color: #333; // support.type.property-name.media
  background-color: #fff; // entity.name.tag.custom
  overflow: scroll; // no scope

  a {
    color: #337ab7;
  }
}
```
